#测试中文
spring:
  datasource:
    #url: jdbc:mysql://120.79.199.48:3306/qidongzi?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://192.168.1.9:3306/qdz?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 100MB #单个文件大小
      max-request-size: 100MB #总文件大小
  qdzmart:
    window-up-load-path-prfix: E:/file/upLoad/
    linux-down-load-path: /usr/local/src/upLoad/
    file-size: 52428800
  redis:
    host: 192.168.1.9
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
    timeout: 10000
  elasticsearch:
    rest:
      uris: 192.168.1.9:9200
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.9:9300
  mail:
    host: smtp.mxhichina.com
    username: qdz@qdzmart.com
    password: Qidongzi123
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
    emailurl: http://127.0.0.1/8081/qdzSupplier/activate?token=
#MyBatis
mybatis-plus:
  mapper-locations: classpath:/com/qdz/qdzmart/dao/xml/*Mapper.xml
  type-enums-package: com.qdz.qdzmart.model.enums
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.qdz.qdzmart.model.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx

  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true

#启动子系统名
qdz:
  system-name: 供应商平台
#Swagger lock
swagger:
  enabled: true
  host:

server:
  port: 8081

#阿里短信服务
aliyuncs:
  accessKeyId: LTAIbL5DPDVsE0Dh
  accessKeySecret: IjnYyO7SUoGB2VqP61R7RuEyWisyiQ
  signName: 启动子
  templateCode1: SMS_164150097 #账号激活

shiro:
  isAudth: true

delivery:
  key: ReHjsNgv4599
  customer: 63A5ECE2DAB7DEA36734B7109A1FDEF4
